### ISSUE TITLE
Exposed AWS Access Key ID Value

### ISSUE THREAD

**Issue by nk9** [amalaguti/CSE#20]
Potential security breach. See /eBay/salt/_modules/compliance_email.py

Particularly this line: `__salt__['smtp.send_msg'](payload['email'], payload['email_subject'], username=`

Found using https://shhgit.darkport.co.uk

**Comment by amalaguti** [comment]
Nick, thanks for the heads up. It was some testing code and the keys are no longer valid I believe, but thanks anyways!


Adrian Malaguti
SaltStack Professional Services
https://saltstack.com/
https://www.linkedin.com/in/adrian-malaguti
